-- ==========================================================
-- TaskFlow Pro - Supabase PostgreSQL Database Schema
-- ==========================================================
-- Run this SQL in your Supabase SQL Editor:
-- https://app.supabase.com/project/_/sql

-- ==========================================================
-- ⚡ QUICK MIGRATION (Agar database pehle se bana hua hai toh sirf ye 3 lines run karein):
-- ==========================================================
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS device_id TEXT DEFAULT NULL;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS device_info TEXT DEFAULT NULL;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS device_locked_at TIMESTAMPTZ DEFAULT NULL;

-- ==========================================================
-- 1. Create USERS table (with Single-Device Lock Security Policy)
-- ==========================================================
CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    name TEXT NOT NULL,
    role TEXT DEFAULT 'student',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    last_login TIMESTAMPTZ,
    device_id TEXT DEFAULT NULL,
    device_info TEXT DEFAULT NULL,
    device_locked_at TIMESTAMPTZ DEFAULT NULL
);

-- ==========================================================
-- 2. Create TASK_PROGRESS table (Current State of Completed Tasks)
-- ==========================================================
CREATE TABLE IF NOT EXISTS public.task_progress (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL,
    task_id TEXT NOT NULL,
    category TEXT DEFAULT 'general',
    is_completed BOOLEAN DEFAULT TRUE,
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_user_task UNIQUE (username, task_id)
);

-- ==========================================================
-- 3. Create TASK_HISTORY table (Timeline of Task Actions)
-- ==========================================================
CREATE TABLE IF NOT EXISTS public.task_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL,
    task_id TEXT NOT NULL,
    task_name TEXT,
    category TEXT DEFAULT 'general',
    action TEXT DEFAULT 'completed', -- 'completed', 'uncompleted', 'reset'
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==========================================================
-- 4. Create LOGIN_HISTORY table (User Login Activity Logs)
-- ==========================================================
CREATE TABLE IF NOT EXISTS public.login_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL,
    login_at TIMESTAMPTZ DEFAULT NOW(),
    user_agent TEXT
);

-- ==========================================================
-- Indexes for High Performance Queries
-- ==========================================================
CREATE INDEX IF NOT EXISTS idx_task_progress_user ON public.task_progress(username);
CREATE INDEX IF NOT EXISTS idx_task_history_user ON public.task_history(username);
CREATE INDEX IF NOT EXISTS idx_login_history_user ON public.login_history(username);

-- ==========================================================
-- Enable Row Level Security (RLS) & Allow Anonymous Web Client Access
-- ==========================================================
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.task_progress ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.task_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.login_history ENABLE ROW LEVEL SECURITY;

-- Allow Public / Anon access for Web Portal (Idempotent: drops if already exists to prevent ERROR 42710)
DROP POLICY IF EXISTS "Allow public read users" ON public.users;
CREATE POLICY "Allow public read users" ON public.users FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public insert users" ON public.users;
CREATE POLICY "Allow public insert users" ON public.users FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public update users" ON public.users;
CREATE POLICY "Allow public update users" ON public.users FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Allow public delete users" ON public.users;
CREATE POLICY "Allow public delete users" ON public.users FOR DELETE USING (true);

DROP POLICY IF EXISTS "Allow public all task_progress" ON public.task_progress;
CREATE POLICY "Allow public all task_progress" ON public.task_progress FOR ALL USING (true);

DROP POLICY IF EXISTS "Allow public all task_history" ON public.task_history;
CREATE POLICY "Allow public all task_history" ON public.task_history FOR ALL USING (true);

DROP POLICY IF EXISTS "Allow public all login_history" ON public.login_history;
CREATE POLICY "Allow public all login_history" ON public.login_history FOR ALL USING (true);

-- ==========================================================
-- Seed Baseline Users & Students
-- ==========================================================
INSERT INTO public.users (username, password, name, role)
VALUES
    ('admin', 'admin123', 'Super Administrator', 'admin'),
    ('papu', 'umerkot123', 'Papu', 'student'),
    ('motiram', 'umerkot123', 'Motiram', 'student'),
    ('saqib', 'sug99', 'Saqib', 'student'),
    ('lajpat', 'lajpatrai', 'Lajpat', 'student'),
    ('dileep', 'dileep123', 'Dileep', 'student'),
    ('zahid', 'mirporkhas123', 'Zahid', 'student'),
    ('chander', 'asdf1234', 'Chander', 'student'),
    ('darshan', 'asdf1234', 'Darshan', 'student'),
    ('farhan', 'asdf1234', 'Farhan', 'student')
ON CONFLICT (username) DO NOTHING;
